name: Build and Deploy Rhythm Runner

on:
  push:
    branches: [ '*' ]  # Deploy all branches
  pull_request:
    branches: [ '*' ]  # Deploy PR builds

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run TypeScript type checking
      run: npm run type-check
    
    - name: Run ESLint code analysis
      run: npm run lint
    
    - name: Run unit tests
      run: npm run test
      
    - name: Build production bundle
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: dist/
        retention-days: 7

  deploy-web:
    name: Deploy to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    # Deploy on pushes to any branch and on pull requests
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Extract branch name
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi
        echo "Deploying branch: $BRANCH_NAME"
    
    - name: Build for production
      run: npm run build
      env:
        NODE_ENV: production
        GITHUB_REF_NAME: ${{ env.BRANCH_NAME }}
    
    - name: Create branch-specific directory
      run: |
        mkdir -p deploy/${{ env.BRANCH_NAME }}
        cp -r dist/* deploy/${{ env.BRANCH_NAME }}/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        keep_files: true  # Keep other branch deployments
        destination_dir: ./
        # cname: rhythm-runner.example.com # Uncomment and update with your domain

  build-mobile:
    name: Mobile Build Preparation
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web version for mobile
      run: npm run build
    
    - name: Check Capacitor setup
      run: |
        if [ -f "capacitor.config.json" ] || [ -f "capacitor.config.ts" ]; then
          echo "Capacitor configured - ready for mobile build"
          npm run capacitor:sync || echo "Capacitor sync failed - mobile setup needed"
        else
          echo "Capacitor not yet configured - run 'npx cap init' to set up mobile builds"
        fi
    
    - name: Upload mobile build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mobile-ready-build
        path: |
          dist/
          android/
          ios/
        retention-days: 30
        if-no-files-found: ignore